apiVersion: v1
entries:
  dummy:
    - apiVersion: v2
      name: dummy
      version: 1.5.0
      created: 2025-08-28T14:30:52.542Z
      digest: 318f0bee626095b8ae0d150e53b20e00aa8e0715b561aa53d606405e60e6df26
      urls:
        - https://mridang.github.io/example-helm/charts/dummy-1.5.0.tgz
      description: A minimal dummy chart
      type: application
      appVersion: 1.0.0
      icon: https://example.test/dummy.svg
      home: https://example.test/dummy
      sources:
        - https://github.com/your-org/dummy
      keywords:
        - demo
        - dummy
        - example
      maintainers:
        - name: Dummy Team
          email: team@example.test
          url: https://example.test
      kubeVersion: ">= 1.24.0-0"
      annotations:
        org.example/category: demo
    - apiVersion: v2
      name: dummy
      version: 1.4.0
      created: 2025-08-28T06:24:58.090Z
      digest: 046840047025e41696e6a5c21747d87e67589d31b5437c5bfc3e03df652d0a00
      urls:
        - https://mridang.github.io/example-helm/charts/dummy-1.4.0.tgz
      description: A minimal dummy chart
      type: application
      appVersion: 1.0.0
      icon: https://example.test/dummy.svg
      home: https://example.test/dummy
      sources:
        - https://github.com/your-org/dummy
      keywords:
        - demo
        - dummy
        - example
      maintainers:
        - name: Dummy Team
          email: team@example.test
          url: https://example.test
      kubeVersion: ">= 1.24.0-0"
      annotations:
        org.example/category: demo
    - apiVersion: v2
      name: dummy
      version: 1.3.2
      created: 2025-08-28T05:58:31.646Z
      digest: 1acc74ac2da76534abde707639bda8434b999fce747d6cad052c4c9ee64e1a2e
      urls:
        - https://mridang.github.io/example-helm/charts/dummy-1.3.2.tgz
      description: A minimal dummy chart
      type: application
      appVersion: 1.0.0
      icon: https://example.test/dummy.svg
      home: https://example.test/dummy
      sources:
        - https://github.com/your-org/dummy
      keywords:
        - demo
        - dummy
        - example
      maintainers:
        - name: Dummy Team
          email: team@example.test
          url: https://example.test
      kubeVersion: ">= 1.24.0-0"
      annotations:
        org.example/category: demo
    - apiVersion: v2
      name: dummy
      version: 1.3.1
      created: 2025-08-27T18:16:27.918Z
      digest: 82143b72dcca4bdeccabf936a3714639eb3ec54d3df95a484c61694e0f74690c
      urls:
        - https://mridang.github.io/example-helm/charts/dummy-1.3.1.tgz
    - apiVersion: v2
      name: dummy
      version: 1.3.0
      created: 2025-08-27T18:08:38.594Z
      digest: 5b077d9f4dd97639f001a944d6f9a81c441b8f6313dce45f3027218d1e26be11
      urls:
        - https://mridang.github.io/example-helm/charts/dummy-1.3.0.tgz
    - apiVersion: v2
      name: dummy
      version: 1.1.0
      created: 2025-08-27T13:28:01.555Z
      digest: 1b954993d61e6292f3afd60f7f93ce025b208a0fdef39bf9e09588eb07b4ec43
      urls:
        - https://mridang.github.io/example-helm/charts/dummy-1.1.0.tgz
generated: 2025-08-28T14:30:52.542Z
