name: Release

on:
  push:
    branches:
      - master

permissions:
  contents: write
  packages: write
  id-token: write
  checks: read

defaults:
  run:
    working-directory: ./

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish-package:
    runs-on: ubuntu-latest
    name: To Artifactory

    steps:
      - name: Runner Common Setup
        uses: mridang/action-runner-common@v1

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Run semantic-release
        uses: mridang/action-semantic-release@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-key: ${{ secrets.DEPLOY_KEY }}
          allow-force-install: 'true'
        env:
          OCI_USERNAME: ${{ github.actor }}
          OCI_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
